enhavo_contact_submit:
    path:     /enhavo/contact/{type}/submit
    defaults: { _controller: EnhavoContactBundle:Contact:submit }
    methods: [POST]

enhavo_contact_sender_mail:
    path: /sendSenderMail
    defaults: { _controller: EnhavoContactBundle:Contact:senderMail }