services:
    enhavo_contact_render:
        class: Enhavo\Bundle\ContactBundle\Twig\ContactForm
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    enhavo_contact_contact:
        class: %enhavo_contact.contact.form%
        arguments:
            - %enhavo_contact.contact.model%
        tags:
            - { name: form.type }

    errorresolver.formerrorresolver:
        class: Enhavo\Bundle\ContactBundle\ErrorResolver\FormErrorResolver
        arguments:
            - @translator